version: "2"
services:

  feedbase:
    build: .
    command: keeper feedbase-daemon
    environment:
      - ETH_ACCOUNT
      - ETH_RPC_URL
      - ETH_RPC_HOST
      - ETH_RPC_PORT
      - HOME
    network_mode: host
    volumes:
      - ./bin:/usr/local/bin:ro
      - ${HOME}/.keeper.json:${HOME}/.keeper.json:ro
