version: "2"
services:
  redis: { image: redis }
  worker: &service
    command: keeper worker
    build: .
    volumes:
      - ./bin:/usr/local/bin:ro
      - ${HOME}/.keeperrc:/root/.keeperrc:ro
    environment: [REDIS_HOST=redis]
    links: [redis]
  clock:
    <<: *service
    command: keeper clock
